//ERRORS
export const SET_ERRORS = "SET_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
//MESSAGE
export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";

//HOME
export const GET_SPECTRUM_STATUS = "GET_SPECTRUM_STATUS";
export const CLEAR_SPECTRUM_STATUS = "CLEAR_SPECTRUM_STATUS";
export const GET_SPECTRUM_WEB_SOCKET_STATUS = "GET_SPECTRUM_WEB_SOCKET_STATUS";